
project:
  type: website
  output-dir: docs

website:
  title: "Tyler Rhee"
  navbar:
    right:
      - text: "About Me"
        href: about.qmd
      - text: "Data Viz"
        menu:
          - text: "Analysis 1"
            href: analysis1.qmd
          - text: "Analysis 2"
            href: analysis2.qmd

format:
  html:
    theme: cosmo

execute:
  warning: false
  message: false